### PR TITLE
Fix qa checks using physical entity.compartment

### PR DESCRIPTION
**Pull request by SolomonShorser-OICR**
The PhysicalEntity class no longer has an attribute named "compartment", but some subclasses still have this attribute. Code that references PhysicalEntity.compartment needs to be updated.

### CODE REVIEW

**Comment by guanmingwu** [comment]
The update should fix the bug. However, the performance may be compromised. The original code needs one SQL call. The new fix needs as many SQL calls as the number of PhysicalEntity instances.

**Comment by SolomonShorser-OICR** [comment]
I don't know how well this code performed before the data model changed, but I ran these two checks on my OICR laptop (CPU is i7-8565U, database is running on the same machine so there's low network lag for db calls) and the program completed in under a minute (16 seconds, to be precise).

If there's a way to improve this code, I'm open to it.

**Comment by guanmingwu** [comment]
Since it runs locally at mid-night every Sunday, let's now worry about the performance. Thanks!

**Comment by SolomonShorser-OICR** [comment]
Ok, I'll merge this soon.

**Pull request merged**
